AWSTemplateFormatVersion: "2010-09-09"
Description: "Associates a Lambda handler with an API stage and deploys it on the gateway for the DSIRE API"



# Imports:

  # GitHubActionsCd:
    # PackageBucketName

  # DsireApi
    # SecurityGroupId
    # SubnetIds
    # ApiId
    # HandlerRoleArn
    # HostingBucket



Parameters:

  Name:
    Type: String
    Description: >
      The name of the handler is used to associate it with a corresponding
      stage on the API Gateway and to fill some friendly naming.



Resources:

  Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures: ["x86_64"]
      CompatibleRuntimes: ["nodejs18.x"]
      LayerName: !Join ['_', ["DsireApi", !Ref Name]]
      Description: !Sub
                     - "External dependencies for the ${NAME} handler."
                     - NAME: !Ref Name
      Content:
        S3Bucket: !ImportValue HostingBucket
        S3Key: "default-layer.zip"

  Handler:
    Type: AWS::Lambda::Function
    DependsOn: Layer
    Properties:
      FunctionName: !Join ['_', ["DsireApi", !Ref Name]]
      Description: !Sub
                     - "The handler for API stage ${NAME}."
                     - NAME: !Ref Name
      Code:
        # The default Lambda code, inlined
        ZipFile: "export const handler = async(event) => ({statusCode: 200, body: JSON.stringify(\"Hello from Lambda!\")})"
      PackageType: Zip
      Runtime: nodejs18.x
      Handler: index.handler
      Timeout: 7
      Role: !ImportValue HandlerRoleArn
      Layers: [!Ref Layer]
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue SecurityGroupId
        SubnetIds: !Split [",", !ImportValue SubnetIds]

  InvokePermission:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html
    # Allow the lambda to fire on its corresponding stage's API Gateway activity
    # https://aws.amazon.com/blogs/compute/using-api-gateway-stage-variables-to-manage-lambda-functions/
    # see "You defined your Lambda function as a stage variable; you must manually give permissions to all
    # the functions you will use..."
    Type: AWS::Lambda::Permission
    DependsOn: Stage
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Handler
      Principal: apigateway.amazonaws.com
      # /*/*/* is stage/request-type/endpoint
      SourceArn: !Sub
                    - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API_ID}/${STAGE_NAME}/*/*
                    - API_ID: !ImportValue ApiId
                      STAGE_NAME: !Ref Name

  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !ImportValue ApiId
    # Don't do this: it creates a default stage for the deployment, but we want a custom one (below)
    #StageName: main

  Stage:
    Type: AWS::ApiGateway::Stage
    DependsOn:
      - Handler
      - Deployment
    Properties:
      RestApiId: !ImportValue ApiId
      DeploymentId: !Ref Deployment
      StageName: !Ref Name
      Variables:
        handler: !Ref Handler
