name: AWS CD
run-name: Build, deploy, and provision AWS

on:
  push:
    branches:
      - main
      - staging
      - testing
  workflow_dispatch:
    inputs:
      forceSync:
        description: "Overwrite all remote content with this build (purge testing)"
        type: boolean
        required: false

permissions:
  id-token: write
  contents: read

jobs:

  build-packages:
    name: Build/bundle TS & package API
    runs-on: ubuntu-latest
    environment: AWS_Development

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Set up Node.js environment version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci package.json

      - name: Build & bundle for production
        env:
          NODE_ENV: production
          AWS_REGION: ${{ vars.AWS_REGION }}
          IDENTITY_EMAIL: ${{ secrets.IDENTITY_EMAIL }}
        run: npm run build
        if: github.ref_name == 'main'

      - name: Build & bundle for staging
        env:
          NODE_ENV: production
          AWS_REGION: ${{ vars.AWS_REGION }}
          IDENTITY_EMAIL: ${{ secrets.IDENTITY_EMAIL }}
        run: npm run build
        if: github.ref_name == 'staging'

      - name: Build & bundle for testing
        env:
          NODE_ENV: development
          AWS_REGION: ${{ vars.AWS_REGION }}
          IDENTITY_EMAIL: ${{ secrets.IDENTITY_EMAIL }}
        run: npm run build
        if: github.ref_name == 'testing'

      - name: Zip API package
        run: zip -j dist/api-${{ github.ref_name }}.zip dist/api/*

      - name: Upload API package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-${{ github.ref_name }}
          path: dist/*.zip

  sync-packages-s3:
    name: Sync API package with S3
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs: build-packages

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Download API package as artifact
        uses: actions/download-artifact@v3
        with:
          name: api-${{ github.ref_name }}
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Sync package with S3
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          FORCE: ${{ inputs.forceSync }}
        run: chmod +x .github/sync-packages.sh; .github/sync-packages.sh

  cloudformation:
    name: Deploy CloudFormation stacks
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs:
      - sync-packages-s3

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Deploy GitHubActionsCd & DsireApi stacks
        run: |
          aws cloudformation deploy --template-file aws/CloudFormation/GitHubActionsCd.yaml --tags product=DsireApi --stack-name GitHubActionsCd --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file aws/CloudFormation/DsireApi.yaml --tags product=DsireApi --stack-name DsireApi --capabilities CAPABILITY_NAMED_IAM

  render-sync-content-s3:
    name: Render & sync content with S3
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs: cloudformation

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Copy content to distribution context
        run: mkdir -p dist/frontend && cp -r frontend dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Get root API URL (for rendering {% API_URL %})
        run: echo "API_URL=$(aws cloudformation list-exports --query "Exports[?Name=='ApiUrl'].Value" --no-paginate --output text)" >> $GITHUB_ENV
      - name: Render and sync content with S3
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          FORCE: ${{ inputs.forceSync }}
        run: chmod +x .github/render-sync-content.sh; .github/render-sync-content.sh

      - name: Upload content as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-${{ github.ref_name }}
          path: dist/frontend/*

  sync-environment-lambda:
    name: Sync secrets with Lambda
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs:
      - cloudformation
      - deploy-packages-lambda

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Sync all environment secrets with Lambda handlers
        env:
          APPROVER_EMAIL_MAIN: ${{ secrets.APPROVER_EMAIL_MAIN }}
          APPROVER_EMAIL_STAGING: ${{ secrets.APPROVER_EMAIL_STAGING }}
          APPROVER_EMAIL_TESTING: ${{ secrets.APPROVER_EMAIL_TESTING }}
          IDENTITY_EMAIL: ${{ secrets.IDENTITY_EMAIL }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: chmod +x .github/sync-env.sh; .github/sync-env.sh

  deploy-packages-lambda:
    name: Deploy API package to Lambda
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs: cloudformation

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Download API package as artifact
        uses: actions/download-artifact@v3
        with:
          name: api-${{ github.ref_name }}
          path: dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Deploy package to Lambda
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          FORCE: ${{ inputs.forceSync }}
        run: chmod +x .github/deploy-packages.sh; .github/deploy-packages.sh
