name: AWS CD
run-name: Build, deploy, and provision AWS

on:
  push:
    branches:
      - main
      - staging
      - testing
  workflow_dispatch:
    inputs:
      forceFillPackages:
        description: "Overwrite all remote packages with this build (purge testing)"
        type: boolean
        required: false

permissions:
  id-token: write
  contents: read

jobs:

  build:
    name: Build and distribute project
    runs-on: ubuntu-latest
    environment: AWS_Development

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Setup Node.js environment version ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci package.json

      - name: Build & bundle for production
        run: NODE_ENV=production npm run build --if-present
        if: github.ref_name == 'main'
      - name: Build & bundle for staging
        run: NODE_ENV=development npm run build --if-present
        if: github.ref_name == 'staging'
      - name: Build & bundle for testing
        run: NODE_ENV=development npm run build --if-present
        if: github.ref_name == 'testing'

      - name: Zip API package and copy frontend statics to distribution context
        run: |
          zip -j dist/${{ github.ref_name }}-api.zip dist/api/*
          cp -r frontend/index.html frontend/styles frontend/images dist/frontend/

      - name: Upload API package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: dist/*.zip
      - name: Upload frontend content as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: dist/frontend/*

  sync-s3:
    name: Sync distributions with S3
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs: build

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Download API package as artifact
        uses: actions/download-artifact@v3
        with:
          name: api
          path: dist/
      - name: Download frontend content as artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: dist/frontend/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      - name: Sync distributions with S3
        run: chmod +x .github/sync-s3.sh; GITHUB_REF_NAME=${{ github.ref_name }} FORCE=${{ inputs.forceFillPackages }} .github/sync-s3.sh

  cloudformation:
    name: Deploy CloudFormation stacks
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs:
      - build
      - sync-s3

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}

      - name: Deploy GitHubActionsCd & DsireApi stacks
        run: |
          aws cloudformation deploy --template-file aws/CloudFormation/GitHubActionsCd.yaml --tags product=DsireApi --stack-name GitHubActionsCd --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation deploy --template-file aws/CloudFormation/DsireApi.yaml --tags product=DsireApi --stack-name DsireApi --capabilities CAPABILITY_NAMED_IAM
