name: AWS Undeploy
run-name: Remove deployment from AWS

on:
  delete:
  workflow_dispatch:

# Required for aws-actions/configure-aws-credentials
permissions:
  id-token: write
  contents: read


jobs:

  get-names:
      name: Get deployment names
      runs-on: ubuntu-latest
      environment: AWS_Development
      outputs:
        NAME: ${{ steps.get-name.outputs.NAME }}
        HANDLER: DsireApi_${{ steps.get-name.outputs.NAME }}
        HANDLER_STACK: DsireApi-${{ steps.get-name.outputs.NAME }}

      steps:

        - name: Generate deployment names for branch ${{ github.ref_name }} (${{ github.event.ref }})
          id: get-name
          env:
            SED_REF_NAME: s~refs/heads/~~g; s~\.~-~g; s~_~-~g; s~/~-~g
          run: |
            NAME=$(echo "${{ github.ref_name }}" | sed "${SED_REF_NAME}")
            echo "NAME=${NAME}" >> $GITHUB_OUTPUT
          if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'


  undeploy-handler:
    name: Remove Lambda handler
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs:
      - get-names

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Remove handler stack
        if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'
        run: aws cloudformation delete-stack --stack-name ${{ needs.get-names.outputs.HANDLER_STACK }}

  delete-content:
    name: Delete S3 content
    runs-on: ubuntu-latest
    environment: AWS_Development
    needs: get-names

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Remove hosted content from S3
        if: github.event.ref_type == 'branch' || github.event_name == 'workflow_dispatch'
        run: aws s3 rm --recursive s3://${{ vars.HOSTING_BUCKET }}/${{ needs.get-names.outputs.NAME }}
